name: "Frogbot Scan Repository"

on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write  # Required for OIDC

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["master"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Frogbot
        uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: rodolphef-benchmarkjava
          oidc-audience: rodolphef-benchmarkjava-audience
        env:
          JF_URL: https://rodolphefplus.jfrog.io
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}